ordering:
  centro-medico-da-familia: ''
  quem-somos: ''
  especialidades: ''
  exames: ''
  contato: ''
items:
  centro-medico-da-familia:
    id: 101
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
  quem-somos:
    id: 105
    columns:
      - 100
  especialidades:
    id: 106
  exames:
    id: 107
  contato:
    id: 108
