version: 2
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1548801250
layout:
  /header/:
    -
      - 'logo-9441 30'
      - 'spacer-3995 70'
  /main/:
    -
      - system-messages-3260
    -
      - system-content-9934
  /footer/:
    -
      - position-footer
    -
      - 'copyright-5592 40'
      - 'spacer-7804 30'
      - 'branding-4051 30'
structure:
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
