name: '11'
timestamp: 1549208781
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1548801250
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-3290: Logo
  position:
    position-position-4486: Header
    position-position-8504: Breadcrumbs
    position-position-9569: Footer
  menu:
    menu-4447: Menu
  messages:
    system-messages-7492: 'System Messages'
  content:
    system-content-4870: 'Page Content'
  copyright:
    copyright-2941: Copyright
  spacer:
    spacer-1921: Spacer
  branding:
    branding-8290: Branding
  mobile-menu:
    mobile-menu-5086: Mobile-menu
inherit:
  default:
    header: header
    logo-3290: logo-8143
    position-position-4486: position-header
    navigation: navigation
    menu-4447: menu-8962
    main: main
    position-position-8504: position-breadcrumbs
    system-messages-7492: system-messages-6771
    system-content-4870: system-content-2949
    footer: footer
    position-position-9569: position-footer
    copyright-2941: copyright-2537
    spacer-1921: spacer-7645
    branding-8290: branding-2751
    offcanvas: offcanvas
    mobile-menu-5086: mobile-menu-4668
