preset: preset3
accent:
  color-1: '#558b2f'
  color-2: '#8bc34a'
header:
  background: '#3c7216'
navigation:
  background: '#558b2f'
showcase:
  background: '#344e2c'
offcanvas:
  background: '#344e2c'
