preset: preset3
accent:
  color-1: '#558b2f'
  color-2: '#8bc34a'
header:
  background: '#3c7216'
navigation:
  background: '#b4e37f'
showcase:
  text-color: '#3c7216'
subfeature:
  text-color: '#4b954b'
footer:
  background: '#7fc76d'
offcanvas:
  background: '#344e2c'
